# Generated by Django 4.2.6 on 2023-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registered_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
