# Generated by Django 4.2.6 on 2023-10-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_data',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
